export const GET_TICKETS = 'GET_TICKETS';
export const DELETE_TICKET = 'DELETE_TICKET';
export const CREATE_TICKET = 'CREATE_TICKET';
export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGES = 'GET_MESSAGES';
export const CREATE_MESSAGE = 'CREATE _MESSAGE';
